# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('caption', models.CharField(max_length=20)),
                ('comments', models.TextField()),
                ('photoimage', models.ImageField(upload_to='instagramimages/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('profileimage', models.ImageField(upload_to='instagramprofile/')),
                ('bio', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram_app.Profile'),
        ),
    ]
