# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=60)),
                ('photoimage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='instagram_app.Image')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='instagram_app.Profile')),
            ],
        ),
    ]
