# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_app', '0002_auto_20181217_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
