# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_app', '0003_auto_20181217_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_comments', to='instagram_app.Image'),
        ),
    ]
